# Maintainer: 0x42697262

pkgname=chicken-settings
pkgver=1.0.3
pkgrel=0
pkgdesc="0x42697262's system configuration, packages, and probably even home config"
url=""
depends=(
    adobe-source-han-sans-cn-fonts
    adobe-source-han-sans-jp-fonts
    adobe-source-han-sans-kr-fonts
    alsa-firmware
    alsa-plugins
    alsa-utils
    amd-ucode
    awesome-terminal-fonts
    bash-completion
    bemenu
    bemenu-wayland
    btop
    btrfs-progs
    cachy-browser
    cachyos-ananicy-rules
    cachyos-hello
    cachyos-kernel-manager
    cachyos-nord-gtk-theme-git
    cachyos-packageinstaller
    cachyos-settings
    cachyos-wallpapers
    cachyos-zsh-config
    cantarell-fonts
    capitaine-cursors
    chwd
    cpupower
    device-mapper
    diffutils
    dmidecode
    dmraid
    dosfstools
    duf
    e2fsprogs
    efibootmgr
    efitools
    exfatprogs
    f2fs-tools
    fastfetch
    ffmpegthumbnailer
    findutils
    freetype2
    fsarchiver
    git
    glances
    grimblast-git
    gst-libav
    gst-plugin-pipewire
    gst-plugins-bad
    gst-plugins-ugly
    haveged
    hdparm
    hwdetect
    hwinfo
    hyprland
    inetutils
    inxi
    iptables-nft
    jfsutils
    kitty
    kvantum
    kvantum-theme-nordic-git
    less
    libdvdcss
    libgsf
    libopenraw
    linux-cachyos-nvidia-open
    linux-firmware
    logrotate
    lsb-release
    lsscsi
    mako
    man-db
    man-pages
    mdadm
    meld
    mesa-utils
    mlocate
    mtools
    neovim
    netcat
    netctl
    nfs-utils
    nilfs-utils
    nmap
    noto-color-emoji-fontconfig
    noto-fonts
    noto-fonts-cjk
    noto-fonts-emoji
    ntp
    nvidia-open
    octopi
    opendesktop-fonts
    openssh
    pacman-contrib
    pamixer
    pavucontrol
    pipewire-alsa
    pipewire-pulse
    pkgfile
    polkit-kde-agent
    poppler-glib
    power-profiles-daemon
    pv
    qt5ct
    rebuild-detector
    reflector
    ripgrep
    rofi
    rofi-emoji
    rsync
    rtkit
    s-nail
    sed
    sg3_utils
    slurp
    smartmontools
    sof-firmware
    swappy
    swaybg
    swaylock-effects-git
    swaylock-fancy-git
    sysfsutils
    texinfo
    ttf-bitstream-vera
    ttf-dejavu
    ttf-liberation
    ttf-meslo-nerd
    ttf-opensans
    udiskie
    unrar
    unzip
    upower
    usb_modeswitch
    usbutils
    vi
    vim
    waybar
    wget
    which
    wireplumber
    wl-clipboard
    wlogout
    wob
    wofi
    wpa_supplicant
    xdg-desktop-portal-hyprland
    xdg-user-dirs
    xdg-utils
    xfsprogs
    xorg-xwayland
    xz
)
arch=('x86_64')
license=()
conflicts=()
source=()
options=()
makedepends=('paru')

prepare() {
    paru -S wl-clipboard-rs
}

build() {
    echo "Building $pkgname..."
}

package() {
    echo "Packaging $pkgname..."
}
